import {ChangeDetectionStrategy, Component, computed, inject, signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {Router} from '@angular/router';
import {InspectionTemplate} from '../../core/models/inspection.models';
import {ToastService} from '../../core/services/toast.service';
import {InspectionStore} from '../../core/state/inspection.store';
import {TemplateStore} from '../../core/state/template.store';

@Component({selector:'app-templates-page',standalone:true,imports:[FormsModule],template:`
<main class="page"><header><div><h1>Inspection templates</h1><p>Standardise field work with reusable checklists and approval rules.</p></div><button class="primary" (click)="dialogOpen.set(true)">＋ New template</button></header>
<section class="toolbar"><label>⌕<input placeholder="Search templates" [ngModel]="query()" (ngModelChange)="query.set($event)"></label><select [ngModel]="category()" (ngModelChange)="category.set($event)"><option>All categories</option><option>Safety</option><option>Quality</option><option>Equipment</option><option>Environment</option></select><span>{{filtered().length}} templates</span></section>
<section class="cards">@for(template of filtered();track template.id){<article [class.inactive]="!template.active"><div class="card-head"><span [attr.data-category]="template.category">{{template.category[0]}}</span><div><small>{{template.category}}</small><h2>{{template.name}}</h2></div><button type="button" class="switch" [class.on]="template.active" (click)="toggle(template)" [attr.aria-label]="template.active ? 'Deactivate template' : 'Activate template'"><i></i></button></div><p>{{template.description}}</p><dl><div><dt>Checklist items</dt><dd>{{template.checklist.length}}</dd></div><div><dt>Photo evidence</dt><dd>{{template.requiresPhotos?'Required':'Optional'}}</dd></div><div><dt>Approval steps</dt><dd>{{template.approvalSteps}}</dd></div></dl><button class="use" [disabled]="!template.active" (click)="use(template)">Use template</button></article>}</section>
@if(!filtered().length){<section class="empty"><span>⌕</span><h2>No matching templates</h2><p>Adjust your search or create a new template.</p><button (click)="query.set('');category.set('All categories')">Clear filters</button></section>}
</main>
@if(dialogOpen()){<div class="backdrop" (click)="dialogOpen.set(false)"><form (click)="$event.stopPropagation()" (ngSubmit)="create()"><header><div><h2>Create template</h2><p>Add a reusable starting point for field teams.</p></div><button type="button" (click)="dialogOpen.set(false)">×</button></header><label><span>Template name</span><input required name="name" [(ngModel)]="draftName" placeholder="e.g. Daily site walk"></label><label><span>Category</span><select name="category" [(ngModel)]="draftCategory"><option>Safety</option><option>Quality</option><option>Equipment</option><option>Environment</option></select></label><label><span>Description</span><textarea name="description" [(ngModel)]="draftDescription" placeholder="Describe when this template should be used"></textarea></label><footer><button type="button" (click)="dialogOpen.set(false)">Cancel</button><button class="primary" [disabled]="!draftName.trim()">Create template</button></footer></form></div>}`,styleUrl:'./templates-page.component.css',changeDetection:ChangeDetectionStrategy.OnPush})
export class TemplatesPageComponent{readonly templates=inject(TemplateStore);private readonly inspections=inject(InspectionStore);private readonly router=inject(Router);private readonly toast=inject(ToastService);readonly query=signal('');readonly category=signal('All categories');readonly dialogOpen=signal(false);draftName='';draftCategory:InspectionTemplate['category']='Safety';draftDescription='';readonly filtered=computed(()=>{const q=this.query().trim().toLowerCase();return this.templates.templates().filter(t=>(this.category()==='All categories'||t.category===this.category())&&(!q||`${t.name} ${t.description}`.toLowerCase().includes(q)));});toggle(template:InspectionTemplate){this.templates.toggle(template.id);this.toast.show(`${template.name} ${template.active?'deactivated':'activated'}.`,'info');}use(template:InspectionTemplate){const item=this.inspections.createFromTemplate(template);void this.router.navigate(['/inspections',item.id]);}create(){if(!this.draftName.trim())return;this.templates.create(this.draftName.trim(),this.draftCategory,this.draftDescription.trim()||'Custom field inspection template.');this.dialogOpen.set(false);this.toast.show('Template created.','success');this.draftName='';this.draftDescription='';}}
