import {ChangeDetectionStrategy, Component, computed, inject} from '@angular/core';
import {DatePipe} from '@angular/common';
import {Router, RouterLink} from '@angular/router';
import {AuthService} from '../../core/auth/auth.service';
import {InspectionStore} from '../../core/state/inspection.store';
import {StatusBadgeComponent} from '../../shared/ui/status-badge/status-badge.component';

@Component({selector:'app-dashboard-page',standalone:true,imports:[DatePipe,RouterLink,StatusBadgeComponent],template:`
<main class="page"><header><div><p class="eyebrow">OPERATIONS OVERVIEW</p><h1>Good morning, {{auth.identity().name}}.</h1><p>Here is what needs attention across your active project.</p></div><a routerLink="/inspections">Open inspection register →</a></header>
<section class="metrics"><button (click)="openStatus('Draft')"><span class="blue">▤</span><div><small>Open drafts</small><strong>{{store.draftCount()}}</strong><em>Continue field work</em></div></button><button (click)="openStatus('Submitted')"><span class="amber">◇</span><div><small>Awaiting approval</small><strong>{{store.submittedCount()}}</strong><em>Review submissions</em></div></button><button (click)="openStatus('Approved')"><span class="green">✓</span><div><small>Approved</small><strong>{{store.approvedCount()}}</strong><em>Completed records</em></div></button><button routerLink="/inspections"><span class="slate">▣</span><div><small>Device save issues</small><strong>{{store.saveFailedCount()}}</strong><em>Review local storage</em></div></button></section>
<div class="grid"><section class="recent"><div class="section-title"><div><h2>Recent inspections</h2><p>Your latest field records and their current status.</p></div><a routerLink="/inspections">View all</a></div>@for(item of recent();track item.id){<button (click)="open(item.id)"><span class="record-icon">▣</span><span><strong>{{item.title}}</strong><small>{{item.id}} · {{item.zone}}</small></span><app-status-badge [value]="item.status"/><em>{{item.updatedAt | date:'medium'}}</em><b>›</b></button>}</section>
<aside><section class="readiness"><div class="section-title"><div><h2>Project readiness</h2><p>Active project</p></div><strong>82%</strong></div><div class="bar"><i></i></div><dl><div><dt>Inspections completed</dt><dd>{{store.approvedCount()}} / {{store.inspections().length}}</dd></div><div><dt>Records saved on device</dt><dd>{{savedCount()}} / {{store.inspections().length}}</dd></div><div><dt>Items requiring review</dt><dd>{{store.submittedCount()}}</dd></div></dl></section><section class="start"><span>＋</span><h2>Start a field inspection</h2><p>Choose an approved template and capture evidence even without a connection.</p><a routerLink="/inspections">New inspection</a></section></aside></div></main>`,styleUrl:'./dashboard-page.component.css',changeDetection:ChangeDetectionStrategy.OnPush})
export class DashboardPageComponent{readonly auth=inject(AuthService);readonly store=inject(InspectionStore);private readonly router=inject(Router);readonly recent=computed(()=>this.store.inspections().slice(0,5));readonly savedCount=computed(()=>this.store.inspections().filter(item=>item.localSaveStatus==='saved').length);open(id:string){void this.router.navigate(['/inspections',id]);}openStatus(status:string){void this.router.navigate(['/inspections'],{queryParams:{status}});}}
